#!/bin/sh
set -e

# Remove obsolete conf files
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/wine.sysctl.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/30-wine.conf -- "$@"
dpkg-maintscript-helper rm_conffile /etc/sysctl.d/31-wine.conf -- "$@"

# Automatically added by dh_installdebconf
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


